version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: ecommerce_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce_db
     
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./Backend
    container_name: ecommerce_backend
    restart: always
    depends_on:
      - mysql
    environment:
      NODE_ENV: production
    ports:
      - "6000:6000"
    volumes:
      - ./Backend:/app
    env_file:
      - ./Backend/.env.production

volumes:
  mysql_data:
